mysite/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace="polls")),
    # url(r'^api/', include('polls.api_urls')), 
    # url(r'^ppal/', include('ppal.urls', namespace="ppal")), 
    
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^employee/$', views.employee, name='employee'),
    url(r'^form/$', views.form, name='form'),
    url(r'^employeeSave/$', views.employeeSave, name='employeeSave'),
    url(r'^employee_del/(.*)/$', views.employee_del, name='employee_del'),
    url(r'^employee_edit/(.*)/$', views.employee_edit, name='employee_edit'),
    url(r'^employee_update/(.*)/$', views.employee_update, name='employee_update'),
    url(r'^calendar/(.*)/$', views.calendar, name='calendar'),
    url(r'^details/(.*)/$', views.details, name='details'),
    url(r'^details_save/$', views.details_save, name='details_save'),
    url(r'^details_display/(.*)/$', views.details_display, name='details_display'),
    url(r'^export/csv/$', views.export_users_csv, name='export_users_csv'),
    url(r'^register/$', views.register, name='register'),
    
    
    url(r'^userLogOut/$', views.userLogOut, name='userLogOut'),
    
    
 
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    
]

polls/models.py
from django.db import models



class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text
    
class Employee(models.Model):
    emp_name = models.CharField(max_length=200)
    emp_age = models.IntegerField(default=1)
    emp_salary = models.IntegerField(default=1000)
    
    def __str__(self):
        return self.emp_name
        
        
class Event(models.Model):
    event_name = models.CharField(max_length=200,default="")
    no_of_people = models.IntegerField(default=1)
   
    start_date = models.DateField(u'Start Day of the event', help_text=u'Start Day of the event')
    end_date = models.DateField(u'End Day of the event', help_text=u' End First Day of the event')
    start_time = models.TimeField(u'Starting time', help_text=u'Starting time')
    end_time = models.TimeField(u'Final time', help_text=u'Final time')
    notes = models.TextField(u'Textual Notes', help_text=u'Textual Notes', blank=True, null=True)

    def __str__(self):
        return str(self.event_name)
    
 


    
    
    

polls/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError


class CustomUserCreationForm(forms.Form):
    username = forms.CharField(label='Enter Username', min_length=4, max_length=150)
    email = forms.EmailField(label='Enter email')
    password1 = forms.CharField(label='Enter password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Username already exists")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")

        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user

polls/views.py
import csv
import pprint
from django.http import Http404
from django.template import loader
from django.shortcuts import get_object_or_404, render , redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm
from django.contrib.auth import login,authenticate, logout 

from rest_framework.views import APIView
from django.contrib.auth import login as django_login, logout as django_logout
from rest_framework.authtoken.models import Token
from rest_framework.response import Response 
from rest_framework.authentication import TokenAuthentication

from django.contrib.auth import authenticate
from rest_framework.decorators import api_view, permission_classes

from django.views.decorators.csrf import csrf_exempt
from rest_framework.permissions import AllowAny
from rest_framework.status import (
    HTTP_400_BAD_REQUEST,
    HTTP_404_NOT_FOUND,
    HTTP_200_OK
)




from rest_framework import viewsets, serializers
from .serializers import EmployeeSerializer

from .models import Question,Choice,Employee,Event
from django.utils.datastructures import MultiValueDictKeyError


def index(request):
    return render(request, 'polls/index.html', )
    
@csrf_exempt
@api_view(["POST"])
@permission_classes((AllowAny,))
def login_api(request):
    username = request.data.get("username")
    password = request.data.get("password")
    if username is None or password is None:
        return Response({'error': 'Please provide both username and password'},
                        status=HTTP_400_BAD_REQUEST)
    user = authenticate(username=username, password=password)
    if not user:
        return Response({'error': 'Invalid Credentials'},
                        status=HTTP_404_NOT_FOUND)
    token, _ = Token.objects.get_or_create(user=user)
    return Response({'token': token.key},
                    status=HTTP_200_OK)
                    
@csrf_exempt
@api_view(["GET"])
def sample_api(request):
    data = {'sample_data': 123}
    return Response(data, status=HTTP_200_OK)
    
    
    
class EmployeeViewSet(viewsets.ModelViewSet):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer
    
def employee(request):
    latest_employee_list = Employee.objects.order_by('emp_name')
    context = {'latest_employee_list': latest_employee_list}
    return render(request, 'polls/employee.html', context)
    
def employee_del(request,id):
    emp = Employee.objects.get(id=id)
    emp.delete()
    latest_employee_list = Employee.objects.order_by('emp_name')
    context = {'latest_employee_list': latest_employee_list}
    return render(request,'polls/employee.html',context)    
 
def employee_edit(request,id):
    
    emp = Employee.objects.get(id=id)
    context = {'emp': emp}
    return render(request,'polls/emp_edit.html',context)    
             
def employee_update(request,id):
    
    emp = Employee.objects.get(id=id)
    emp_name = request.POST['name']
    emp_age= request.POST['age']
    emp_salary= request.POST['salary']
    emp.emp_name = emp_name
    emp.emp_age = emp_age
    emp.emp_salary = emp_salary    
    emp.save()
    
    latest_employee_list = Employee.objects.order_by('emp_name')
    context = {'latest_employee_list': latest_employee_list}
    return render(request, 'polls/employee.html', context)
        
def form(request):
    latest_form_list = Employee.objects.order_by('emp_name')
    context = {'latest_form_list': latest_form_list}
    return render(request, 'polls/form.html', context)
    
def employeeSave(request):
    pprint.pprint(request.POST)
    emp_name = request.POST['name']
    emp_age= request.POST['age']
    emp_salary= request.POST['salary']
    if Employee.objects.filter(emp_name=emp_name).exists():
        latest_employee_list = Employee.objects.order_by('emp_name')
        context = {'latest_employee_list': latest_employee_list,'employee_error': 'NAME ALREADY EXITS...'}
        return render(request, 'polls/employee.html', context)
    else:
        pprint.pprint("employee name is: "+str(emp_name))
        pprint.pprint("employee age is: "+str(emp_age))
        pprint.pprint("employee salary is: "+str(emp_salary))
        Employee_instance=Employee.objects.create(emp_name=emp_name,emp_age=emp_age,emp_salary=emp_salary)
        latest_employee_list = Employee.objects.order_by('emp_name')
        context = {'latest_employee_list': latest_employee_list}
        return render(request, 'polls/employee.html', context)
    

    
def login(request):
    user_name = request.POST['email']
    password = request.POST['password']
    pprint.pprint("Username is: "+str(user_name))
    pprint.pprint("Password is: "+str(password))
    context={}
    if authenticate(username=user_name,password=password):
        pprint.pprint("Proper User..Please come in!!!!")
        return render(request, 'polls/home_page.html', context)
    else:
        context={'error_msg':'Invalid username or password'}
        return render(request, 'polls/index.html', context)
        
def userLogOut(request):
    logout(request)
    context={'error_msg':'Logged out successfully'}
    return render(request, 'polls/index.html', context)
    
    
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    return HttpResponse("You're voting on question %s." % question_id)
    
def calendar(request,id):
    emp = Employee.objects.get(id=id)
    context = {'emp': emp}
    return render(request, 'polls/calendar.html',context)
    
    
def details(request,id):
    emp = Employee.objects.get(id=id)
    context = {'emp': emp}
    return render(request, 'polls/calendar3.html',context)
    
    
def details_save(request):
    pprint.pprint(request.POST)
    event_name = request.POST['eventname']
    no_of_people = request.POST['no-of-people']
    start_date = request.POST['start_date']
    start_time = request.POST['start_time']
    end_date = request.POST['end_date']
    end_time = request.POST['end_time']
    notes = request.POST['description']
    Event_instance=Event.objects.create(event_name=event_name,no_of_people=no_of_people,start_date=start_date,start_time=start_time,end_date=end_date,end_time=end_time,notes=notes)
    pprint.pprint("Event name is: " +str(Event_instance))
    event_list = Event.objects.all()
    context = {'event_list':event_list}
    return render(request, 'polls/calendar3.html',context)
    
def details_display(request,id):
    
    emp = Employee.objects.get(id=id)
    event_list = Event.objects.filter(start_date=timezone.now())
    context = {'event_list': event_list,'emp': emp}
    return render(request, 'polls/cal_display.html',context)
    
    
def employee_update(request,id):
    emp = Employee.objects.get(id=id)
    emp_name = request.POST['name']
    emp_age= request.POST['age']
    emp_salary= request.POST['salary']
    
    if Employee.objects.filter(emp_name=emp_name).exists():
        latest_employee_list = Employee.objects.order_by('emp_name')
        context = {'latest_employee_list': latest_employee_list,'employee_error': 'NAME ALREADY EXITS...'}
        return render(request, 'polls/employee.html', context)
    else:
        emp.emp_name = emp_name
        emp.emp_age = emp_age
        emp.emp_salary = emp_salary    
        emp.save()
        latest_employee_list = Employee.objects.order_by('emp_name')
        context = {'latest_employee_list': latest_employee_list}
        return render(request, 'polls/employee.html', context)
        
def export_users_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="Employee.csv"'

    writer = csv.writer(response)
    writer.writerow(['Emp_name','Emp_age','Emp_salary'])

    users = Employee.objects.order_by('emp_name').values_list('emp_name','emp_age','emp_salary')
    for user in users:
        writer.writerow(user)

    return response
    
def register(request):
    if request.method == 'POST':
        f = CustomUserCreationForm(request.POST)
        if f.is_valid():
            f.save()
            messages.success(request, 'Account created successfully')
            context = {'msg': 'Account created successfully Please Log In..'}
            return render(request, 'polls/index.html',context)

    else:
        f = CustomUserCreationForm()

    return render(request, 'polls/register.html', {'form': f})

    
    
# class LoginView(APIView):
    # def post(self, request):
        # serializer = LoginSerializer(data=request.data)
        # serializer.is_valid(raise_exceptions=True)
        # user = serializer.validated_data["user"]
        # django_login(request, user)

polls/templates/polls/base.html
<html>


    
<a href="{% url 'polls:userLogOut' %}">Logout</a>
        
        
 {% block a %}
 {% endblock %}
</html>

polls/templates/polls/cal_display.html
<html>
{% extends 'polls/base.html' %}

{% block a %}

<br/>
<br/>


{% load static %}
<head>
<link  href={% static "css/employee.css" %} rel="stylesheet">
</head>

<h2>{{ emp.emp_name }}</h2>


<table>
    <label><font size =30,font color ="blue"><p align=left>EVENT DETAILS </p></font></label>
    <thead>
        <tr>
            <th>EVENT_NAME</th>
            <th>NO_OF_PEOPLE</th>
            <th>START_DATE</th>
            <th>END_DATE</th>
            <th>START_TIME</th>
            <th>END_TIME</th>
            <th>NOTES</th>
        </tr>
    </thead>
    <tbody>
    <div>
    
    
    {% for event in event_list %}
        <tr>
         <td>{{ event.event_name }}</td>
         <td>{{ event.no_of_people }}</td>
         <td>{{ event.start_date }}</td>
         <td>{{ event.end_date }}</td>
         <td>{{ event.start_time }}</td>
         <td>{{ event.end_time }}</td>
         <td>{{ event.notes }}</td>
         
        </tr>
    {% endfor %}
    
    </form>
    
    </div>
    
        
    
    </tbody>
 
</table>

{% endblock %}
           
</html>

polls/templates/polls/calendar.html
<html>

{% extends 'polls/base.html' %}

{% block a %}
<br/>
<br/>
<title> CALENDAR </title>
{% load static %}
<link rel="stylesheet" href="{% static "css/style1.css" %}" />
 <body>
 
 <div class="container">
   <div class="row">
     {{  emp.id }}
    {% include 'polls/calendar_new.html' %}
      
   </div>
</div>

</body>
{% endblock %}
</html>   

polls/templates/polls/calendar3.html
<html lang="en">
<br/>
{% extends 'polls/base.html' %}


{% block a %}
{% load static %}
<head>
  <meta charset="utf-8">
  <title>Calendar</title>
  <meta name="description" content="Calendar">
  <meta name="author" content="Charles Anderson">
  <link rel="stylesheet" href={% static "css/calendar3.css" %}>

</head>

<body>

  <div class="content">
    <div class="calendar-container">
      <div class="calendar"> 
        <div class="year-header"> 
          <span class="left-button" id="prev"> &lang; </span> 
          <span class="year" id="label"></span> 
          <span class="right-button" id="next"> &rang; </span>
        </div> 
        <table class="months-table"> 
          <tbody>
            <tr class="months-row">
              <td class="month">Jan</td> 
              <td class="month">Feb</td> 
              <td class="month">Mar</td> 
              <td class="month">Apr</td> 
              <td class="month">May</td> 
              <td class="month">Jun</td> 
              <td class="month">Jul</td>
              <td class="month">Aug</td> 
              <td class="month">Sep</td> 
              <td class="month">Oct</td>          
              <td class="month">Nov</td>
              <td class="month">Dec</td>
            </tr>
          </tbody>
        </table> 
        
        <table class="days-table"> 
          <td class="day">Sun</td>  
          <td class="day">Mon</td> 
          <td class="day">Tue</td> 
          <td class="day">Wed</td> 
          <td class="day">Thu</td> 
          <td class="day">Fri</td> 
          <td class="day">Sat</td>
        </table>
        <h2>Profile Name:{{ emp.emp_name}}</h2>  
        
        <div class="frame"> 
          <table class="dates-table"> 
              <tbody class="tbody">             
              </tbody> 
          </table>
        </div>
       <button class="button" id="add-button">Add Event</button>
 <a href="{% url 'polls:details_display' emp.id s %}"><button class="button" id="get-button">Get Details</button></a>
         </div>
    </div>
    <div class="events-container">
    </div>
    <div class="dialog" id="dialog">
        <h2 class="dialog-header"> Add New Event </h2>
        <form class="form" id="form" action="{% url 'polls:details_save' %}" method="post" >
         {% csrf_token %}
          <div class="form-container" align="center">
            <label class="form-label" id="valueFromMyButton" for="name">Event name</label>
            <input class="input" type="text" id="name" name="eventname" maxlength="36">
            <label class="form-label" id="valueFromMyButton" for="count">Number of people to invite</label>
            <input class="input" type="number" id="count" name="no-of-people" min="1" max="1000000" maxlength="7">
            <label for="start">Start Event</label>
            <input type="date" id="start" name="start_date" value="" />
            <input type="time" id="start" name="start_time" min="9:00" max="18:00" required />
            <br/>
            <br/>
            <label for="end">End Event</label>
            <input type="date" id="end" name="end_date" value="" / >
            <input type="time" id="end" name="end_time" min="9:00" max="18:00" required />
            <br/>
            <br/>
            <textarea rows="3" cols="50" name="description" placeholder="write the description here."></textarea> 
            <br/>            
            <input type="submit" value="OK" class="button" id="ok-button">
            <input type="button" value="Cancel" class="button" id="cancel-button">
            
          </div>
         </form>
      </div>
  </div>
  <!-- Dialog Box-->
  
  
  <script src={% static "js/calendar3.1.js" %}
    
  </script>
  
  
</script>
  <script src={% static "js/calendar3.js" %}></script>
</body>

{% endblock %}
</html>

polls/templates/polls/calendar_new.html
<html>

 <div class="calendar_entry col-lg-4">
     <h2>{{ emp.emp_name}}</h2>
     
     <br/>
  <a href="{% url 'polls:details' emp.id %}"><button class=" btn btn-primary">view Details</button>
    </a> 
    </div>
    
 </html>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/emp_edit.html
<html>
{% extends 'polls/base.html' %}

{% block a %}
<br/>
<br/>
<body>
<form action="{% url 'polls:employee_update' emp.id %}" method="post">
{% csrf_token %}
   {{ emp.id }}
   <input type="text" name="name" value={{ emp.emp_name }}></input>
   <input type="number" name="age" value={{ emp.emp_age }}></input>
   <input type="number" name="salary"  value={{ emp.emp_salary }}></input>
   <button type="submit" >save</button>
   
</form>
</body>
{% endblock %}
</html>

polls/templates/polls/employee.html
<html>
{% extends 'polls/base.html' %}

{% block a %}

<br/>
<br/>

{% load static %}
<head>
<link  href={% static "css/employee.css" %} rel="stylesheet">
</head>


<a href="{% url 'polls:form' %}"> Add New Employee </a>
<br/>
<br/>
<a href="{% url 'polls:export_users_csv' %}">Download</a>
<br/>
<br/>
<br/>
{{ employee_error }}
<br/>

<table>
    <label><font size =30,font color ="blue"><p align=left>Employee Table </p></font></label>
    <thead>
        <tr>
            <th>emp_name</th>
            <th >emp_age</th>
            <th >emp_salary</th>
            <th>Edit_button</th>
            <th>Delete_button</th>
        </tr>
    </thead>
    <tbody>
    <div>
    
    
    {% for employee in latest_employee_list %}
        <tr>
         <td>{{ employee.emp_name }}</td>
         <td>{{ employee.emp_age }}</td>
         <td>{{ employee.emp_salary }}</td>
         <td><a href="{% url 'polls:employee_edit' employee.id %}"><button type="button">Edit</button> </a></td>
         <td><a href="{% url 'polls:employee_del' employee.id %}"><button type="button">Delete</button></a></td>
        </tr>
    {% endfor %}
    
    </form>
    
    </div>
    
        
    
    </tbody>
 
</table>


{% endblock %}
           


</html>

polls/templates/polls/fail_page.html
<html>
you are successfully logged in 
</html>

polls/templates/polls/form.html
<html>
{% extends 'polls/base.html' %}

{% block a %}

<head>
<title>Popup Employee form</title>

<script src="js/my_js.js"></script>
</head>
<!-- Body Starts Here -->
<body id="body" style="overflow:hidden;">
<div id="abc">
<!-- Popup Div Starts Here -->
<div id="popupEmployee">
<!-- Contact Us Form -->
<form id="demo" action="{% url 'polls:employeeSave' %}" method="post" >
{% csrf_token %}
<h2>EMPLOYEE</h2>
<hr>
<input id="name" name="name" placeholder="Name" type="text">
<input id="age" name="age" placeholder="Age" type="number">
<input id="salary" name="salary" placeholder="Salary" type="number">

<button type="submit">submit</button>
</form>
</div>
<!-- Popup Div Ends Here -->
</div>

</body>
<!-- Body Ends Here -->

{% endblock %}
</html>

polls/templates/polls/home_page.html
<HTML>

<br/>
<br/>

YOU ARE SUCCESSFULLY LOGGED IN
 <br/>
 <br/>

 <a href="{% url 'polls:employee' %}">click here to go to employee page </a>

</HTML>

polls/templates/polls/index.html
<!--Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html lang="zxx">
{% load static %}
<head>
	<title>login page created by prashanth</title>
	<!-- Meta tag Keywords -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8" />
	<meta name="keywords" content="Validify Login Form Responsive Widget,Login form widgets, Sign up Web forms , Login signup Responsive web form,Flat Pricing table,Flat Drop downs,Registration Forms,News letter Forms,Elements"
	/>
	<script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<!-- Meta tag Keywords -->
	<!-- css files -->
	<link rel="stylesheet" href={% static "css/style.css" %} type="text/css" media="all" />
	<!-- Style-CSS -->
	<link  href={% static "css/fontawesome-all.css" %} rel="stylesheet">
	<!-- Font-Awesome-Icons-CSS -->
	<!-- //css files -->
	<!-- web-fonts -->
	<link href={% static "webfonts/nova_round.css" %} rel="stylesheet">
	<link href={% static "webfonts/open_sans.css" %} rel="stylesheet">
	<!-- //web-fonts -->
</head>

<body>
	<!-- title -->
	<h1>
		<span>V</span>alidify
		<span>L</span>ogin
		<span>F</span>orm
	</h1>
    
    
    
	<!-- //title -->
	<!-- content -->
    {% if error_msg %}
    <p style="color:red">{{error_msg}}</p>
    {% endif %}
    <p style="color:red">{{ msg }}</p>
	<div class="sub-main-w3">
		<form id="demo" action="{% url 'polls:login' %}" method="post" >
            {% csrf_token %}
			<h2>Login To Your Account</h2>
			<div class="form-group">
				<input type="text" class="form-control textbox" name="email" placeholder="Username" required="">
			</div>
			<div class="form-group">
				<input type="password" class="form-control textbox" name="password" placeholder="Password" required="">
			</div>
			<div class="form-group-2">
				<button class="btn btn-default btn-osx btn-lg" type="submit">Submit
				</button>
                <button class="btn btn-default btn-osx btn-lg" type="submit">
               <a href="{% url 'polls:register' %}">SignUp</a>
                </button>
			</div> 
            
			<div class="alert alert-success hidden" role="alert">You Have Successfully Logged In</div>
		</form>
       
        
		<!-- //switch -->
	</div>
	<!-- //content -->
  

	<!-- copyright -->
	<div class="footer">
		<p>&copy; 2018 Validify Login Form. All rights reserved | Design by
			<a href="http://w3layouts.com">W3layouts</a>
		</p>
	</div>
	<!-- //copyright -->
     
	<!-- Jquery -->
	<script src={% static "js/jquery-2.2.3.min.js" %}></script>
	<!-- //Jquery -->
	<!-- validify plugin -->
	
	<!-- //validify plugin -->

</body>

</html>

polls/templates/polls/index_old.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}